### PR TITLE
Refine Wording When Copying ace.js

### PR DESCRIPTION
**Pull request by marcuspoehls**
### ❓ Type of change

- [x] 📝 Wording refinement
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Minor wording refinement for the log message when copying the `ace.js` file.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @marcuspoehls! 👋🏻 

We don´t copy the file, we entirely rewrite it. That's why there's a warning inside, advising against adding any extra content.

**Comment by marcuspoehls** [comment]
@RomainLanz Hey Romain, you’re right. My bad. I’ve updated my merge request to change the log message from `rewrited …` to `created …`. Maybe you’re open to this log message refinement 🙂

**Comment by thetutlage** [comment]
@RomainLanz I think we can go with `created` keyword. Because, we never rewrite the same `ace` file. Instead we creating a fresh one inside the `build` folder. What do you think?

**Review by RomainLanz — APPROVED** [review]
LGTM

**Comment by marcuspoehls** [comment]
Cool 🙂

**Pull request merged**
